global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: ERROR
  format: common
  filePath: /var/log/traefik/traefik.log

accesslog:
  format: json
  filePath: /var/log/traefik/access.log

api:
  dashboard: true
  disableDashboardAd: true
  insecure: true


entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  cloudflare-staging:
    acme:
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
  cloudflare:
    acme:
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  docker:
    exposedByDefault: false
    endpoint: "tcp://socket-proxy:2375"
  file:
    directory: /etc/traefik
    watch: true
