services:
  readarr:
    image: lscr.io/linuxserver/readarr:latest
    restart: unless-stopped
    networks:
      - media_center_network
    environment:
      - PUID=${COMPOSE_USER_ID}
      - PGID=${COMPOSE_GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIRECTORY}/readarr:/config
      - ${DATA_DIRECTORY}:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - "traefik.enable=true"
      - "traefik.http.routers.readarr.rule=Host(`${READARR_EXTERNAL_ADDR}`)"
      - "traefik.http.routers.readarr.entrypoints=websecure"
      - "traefik.http.routers.readarr.tls=true"
      - "traefik.http.services.readarr.loadbalancer.server.port=8787"
      - "traefik.http.routers.readarr.tls.certresolver=${CERTIFICATE_RESOLVER_NAME}"
