services:
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    user: ${COMPOSE_USER_ID}:${COMPOSE_GROUP_ID}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${WHOAMI_EXTERNAL_ADDR}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=${CERTIFICATE_RESOLVER_NAME}"
    networks:
      - media_center_network
