services:
  qbittorrent-nox:
    container_name: qbittorrent-nox
    network_mode: "container:gluetun"
    environment:
      - PAGID=${QBITTORRENT_PAGID}
      - PGID=${COMPOSE_GROUP_ID}
      - PUID=${COMPOSE_USER_ID}
      - QBT_LEGAL_NOTICE=confirm
      - QBT_VERSION=latest
      - QBT_WEBUI_PORT=${QBITTORRENT_WEBUI_PORT}
      - TZ=${TIMEZONE}
    image: qbittorrentofficial/qbittorrent-nox:latest
    read_only: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - ${APP_DATA_DIRECTORY}/qbittorrent-nox:/config
      - ${DATA_DIRECTORY}/torrents:/data/torrents
    restart: unless-stopped
    depends_on:
     - gluetun
    labels:
      - com.centurylinklabs.watchtower.enable=true

