services:
  qbittorrent-nox:
    # for debugging
    #cap_add:
      #- SYS_PTRACE
    container_name: qbittorrent-nox
    network_mode: "container:gluetun"
    environment:
      #- PAGID=10000
      - PGID=${COMPOSE_GROUP_ID}
      - PUID=${COMPOSE_USER_ID}
      - QBT_LEGAL_NOTICE=confirm
      - QBT_VERSION=latest
      - QBT_WEBUI_PORT=${QBITTORRENT_WEBUI_PORT}
      - TZ=${TIMEZONE}
      #- UMASK=022
    image: qbittorrentofficial/qbittorrent-nox:latest
    read_only: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - ${SERVICE_CONFIGURATIONS_DIRECTORY}/qbittorrent-nox:/config
      - ${DATA_DIRECTORY}/torrents:/data/torrents
    restart: unless-stopped
    depends_on:
     - gluetun
    labels:
      - com.centurylinklabs.watchtower.enable=true

