###########################################################################
###########################################################################
##
##  Docker Compose File: Docker Media Center
##  Function: Everything related to managing a media center
##
##  VPN: Deluge, Prowlarr, FlareSolverr
##
##  Non-VPN: Jellyfin, Radarr, Buildarr, Watchtower
##
###########################################################################
###########################################################################

name: docker-media-center

#===============================================================================
# Networks
#===============================================================================
networks:
  default:
    driver: bridge

#===============================================================================
# Included services
#===============================================================================
include:
  # CORE
  - ./services/traefik/compose.yaml
  - ./services/whoami/compose.yaml
  # MEDIA
  # UTILITIES
