###########################################################################
###########################################################################
##
##  Docker Compose File: Docker Media Center
##  Function: Everything related to managing a media center
##
##  VPN: Deluge, Prowlarr, FlareSolverr
##
##  Non-VPN: Jellyfin, Radarr, Buildarr, Watchtower
##
###########################################################################
###########################################################################

name: docker-media-center

#===============================================================================
# Networks
#===============================================================================
networks:
  media_center_network:
    external: true
    name: ${MEDIA_CENTER_NETWORK}
  socket_proxy:
    name: socket_proxy
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 192.168.91.0/24
#===============================================================================
# Included services
#===============================================================================
include:
  - path:
    - ./services/traefik/compose.yaml
    env_file: ${GLOBAL_ENV_FILE_PATH}
  - path:
    - ./services/whoami/compose.yaml
    env_file: ${GLOBAL_ENV_FILE_PATH}
  - path:
    - ./services/dozzle/compose.yaml
    env_file: ${GLOBAL_ENV_FILE_PATH}
  - path:
    - ./services/socket-proxy/compose.yaml
    env_file: ${GLOBAL_ENV_FILE_PATH}
  - path:
    - ./services/watchtower/compose.yaml
    env_file: ${GLOBAL_ENV_FILE_PATH}
  - path:
    - ./services/teleport/compose.yaml
    env_file: ${GLOBAL_ENV_FILE_PATH}
