###########################################################################
###########################################################################
##
##  Docker Compose File: Docker Media Center
##  Function: Everything related to managing a media center
##
##  VPN: Deluge, Prowlarr, FlareSolverr
##
##  Non-VPN: Jellyfin, Radarr, Buildarr, Watchtower
##
###########################################################################
###########################################################################

name: docker-media-center

#===============================================================================
# Networks
#===============================================================================
networks:
  media_center_network:
    external: true
    name: ${MEDIA_CENTER_NETWORK}
#===============================================================================
# Included services
#===============================================================================
include:
  - path:
  # CORE
    - ./services/traefik/compose.yaml
    - ./services/whoami/compose.yaml
    env_file: ${GLOBAL_ENV_FILE_PATH}
  # MEDIA
  # UTILITIES
