services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless-debug:16.4.7
    container_name: teleport
    volumes:
      - ${SERVICE_CONFIGURATIONS_DIRECTORY}/teleport:/etc/teleport
      - ${APP_DATA_DIRECTORY}/teleport:/var/lib/teleport
    environment:
      - TELEPORT_EXTERNAL_ADDR=${TELEPORT_EXTERNAL_ADDR}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.teleport.loadbalancer.serversTransport=insecureSkipVerifyEnabledServersTransport@file"
      - "traefik.http.services.teleport.loadbalancer.server.port=3080"
      - "traefik.http.services.teleport.loadbalancer.server.scheme=https"
      - "traefik.http.routers.teleport-https.entrypoints=websecure"
      - "traefik.http.routers.teleport-https.rule=Host(`${TELEPORT_EXTERNAL_ADDR}`) || HostRegexp(`[a-z]+.${TELEPORT_EXTERNAL_ADDR}`)"
      - "traefik.http.routers.teleport-https.tls=true"
      - "traefik.http.routers.teleport-https.tls.certresolver=${CERTIFICATE_RESOLVER_NAME}"
      - "traefik.http.routers.teleport-https.tls.domains[0].main=${TELEPORT_EXTERNAL_ADDR}"
      - "traefik.http.routers.teleport-https.tls.domains[0].sans=*.${TELEPORT_EXTERNAL_ADDR}"
    networks:
      - media_center_network
    restart: unless-stopped
    command: --insecure # until certificat setup completed
