services:
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    networks:
      - media_center_network
    environment:
      - PUID=${COMPOSE_USER_ID}
      - PGID=${COMPOSE_GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIRECTORY}/lidarr:/config
      - ${DATA_DIRECTORY}:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.rule=Host(`${LIDARR_EXTERNAL_ADDR}`)"
      - "traefik.http.routers.lidarr.entrypoints=websecure"
      - "traefik.http.routers.lidarr.tls=true"
      - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
      - "traefik.http.routers.lidarr.tls.certresolver=${CERTIFICATE_RESOLVER_NAME}"
